### ISSUE TITLE
problem with fbterm colors

### ISSUE THREAD

**Issue by ragnarov** [OliverLew/dotfiles#2]
Are you using some special patch for fbterm?
I can't change the foreground and background colors the way you did.
I am using this : https://aur.archlinux.org/packages/fbterm

**Comment by xlucn** [comment]
Just checked the AUR package, indeed does not work with my fbtermrc. I am forking some (I forgot exactly which repo) patched version on GitHub, my fork is [here](https://github.com/OliverLew/fbterm). This one has a commit to patch [configurable colour palette](https://github.com/OliverLew/fbterm/commit/71a7a794a0df613595321381b1c55d3e44c077ce).
If I am not wrong, the old AUR package (fbterm had been removed from AUR once before) was also based on some GitHub repo, which had the color palette patch.

As for the current AUR (or debian) package, colors can only be changed with fbterm's own escape sequence:
```sh
printf "\033[3;0;33;33;33}" # color0 is now #212121
```

**Comment by ragnarov** [comment]
Thank you for replying.
I have applied that patch.
I can change:
```
color-0=212121
color-1=826023
color-2=618231
color-3=7e7b28
color-4=3e825c
color-5=82685c
color-6=749cb3
color-7=a6a19b
color-8=484848
color-9=b48430
color-10=86b443
color-11=b0ab37
color-12=55b47f
color-13=b4907f
color-14=9bb4c8
color-15=d8d1c9
```
But these don't work:
```
color-foreground=a6a19b
color-background=212121
```
Can you confirm that only changing `color-foreground` and `color-background` works.
Without using :
```
color-0=212121
color-1=826023
color-2=618231
color-3=7e7b28
color-4=3e825c
color-5=82685c
color-6=749cb3
color-7=a6a19b
color-8=484848
color-9=b48430
color-10=86b443
color-11=b0ab37
color-12=55b47f
color-13=b4907f
color-14=9bb4c8
color-15=d8d1c9
```

**Comment by xlucn** [comment]
Confirmed. Looking through the code, reason is the patch only changes the first 16 colors, so `color-{fore,back}ground` still can not set to rgb values. I guess I was hoping them to.

**Comment by ragnarov** [comment]
> Can you confirm that only changing `color-foreground` and `color-background` works. Without using :





> Confirmed. Looking through the code, reason is the patch only changes the first 16 colors, so `color-{fore,back}ground` still can not set to rgb values. I guess I was hoping them to.

I assume this does not work.
(i.e. just using the options `color-foreground` and `color-background` do not work)
So is there some solution?
Will you make another patch?
Can I please have it? :D

**Comment by xlucn** [comment]
Seems hard to do. In the code foreground and background colors are always represented by an index number of the palette. In other words, you can only choose colors in the 256-color palette.

If you just want different fg and bg from base-16 colors, the only workaround is to define some color in the palette first, and assign that to either foreground or background color. I made a little change to the code, see [the latest commit](https://github.com/OliverLew/fbterm/commit/fc1569fd488aa0089601836e467bbd5562815728). You can change similar colors, e.g., color-232 to color-255 are grey scales (from dark to bright), to the ones you like:
```
color-235=212121
color-247=a6a19b
color-background=235
color-foreground=247
```

**Comment by ragnarov** [comment]
> ... In the code foreground and background colors are always represented by an index number of the palette. In other words, you can only choose colors in the 256-color palette.
>```
> color-background=235
> color-foreground=247
> ```

For me, even after applying the first patch, I can't use those 256 colors.
As if I did not set any config.

Does this code work for you?
```
color-background=235
color-foreground=247
```

Is there some other patch that I should use for this?

Okay. I have built and tried your fork and it seems the following code does work.
```
color-background=235
color-foreground=247
```
So it seems I need both the latest patch and the first patch. But I am not sure.

Edit:

Awesome.
I have applied the two commits as patch on the aur version and the following code works:
```
color-background=235
color-foreground=247
```

Thanks you @OliverLew

**Comment by xlucn** [comment]
Right, I forgot to correct that after I came up with the fix. By default bg and fg only use color 0-7. Good to know it works.
